name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  LEADERBOARD_IMAGE_NAME: minecraft-leaderboard-updater
  FRONT_IMAGE_NAME: minecraft-leaderboard-frontend
  REGISTRY: ghcr.io
  IMAGE_OWNER: thibautchoppy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Correct authentication for GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Generate the tag based on the current date
    - name: Set TAG variable
      run: echo "TAG=$(date +%Y-%m-%d)" >> $GITHUB_ENV

    # Build and push the leaderboard-updater image
    - name: Build and push leaderboard-updater
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.LEADERBOARD_IMAGE_NAME }}:${{ env.TAG }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.LEADERBOARD_IMAGE_NAME }}:latest

    # Build and push the frontend image
    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: frontend
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.FRONT_IMAGE_NAME }}:${{ env.TAG }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.FRONT_IMAGE_NAME }}:latest
