name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  LEADERBOARD_IMAGE_NAME: minecraft-leaderboard-updater
  FRONT_IMAGE_NAME: minecraft-leaderboard-frontend
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Docker registry Login
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build & push of leaderboard-updater image
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.LEADERBOARD_IMAGE_NAME }}:$(date +%Y-%m-%d)
          ${{ env.REGISTRY }}/${{ env.LEADERBOARD_IMAGE_NAME }}:latest

    # Build & push of frontend image
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: frontend
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.FRONT_IMAGE_NAME }}:$(date +%Y-%m-%d)
          ${{ env.REGISTRY }}/${{ env.FRONT_IMAGE_NAME }}:latest
